services:
  websites:
    build: 
      context: .
    ports:
      - "80:80"
  unit-tests:
    volumes:
      - "${PWD}/app:/app"
    build:
      context: .
      dockerfile: rspec.dockerfile        
    command:
      - --pattern
      - /app/spec/unit/*_spec.rb

