services:
  websites:
    build: 
      context: .  # Build the web service from the current directory
    ports:
      - "80:80"
  unit-tests:
    volumes:
      - "$PWD:/app"  # This mounts the spec directory to /spec in the container
    build:
      context: .  # Build context for the unit-tests service
      dockerfile: rspec.dockerfile        
    command: 
      - rspec
      - --pattern
      - "/spec/unit/*_spec.rb"  # Updated to point to the correct path for your test files
